swagger: "2.0"
info:
  description: "API Documentation for the Conversation Echo API."
  version: "1.1.0"
  title: "Conversation Echo API"
host: "csjar37r18.execute-api.eu-central-1.amazonaws.com/dev"
tags:
- name: "conversations"
  description: "Everything about conversations"
- name: "user"
  description: "Everything about user"
schemes:
- "https"
paths:
  /conversations:
    get:
      tags:
      - "conversations"
      summary: "Get all conversations of current user"
      description: ""
      operationId: "getAllConversations"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Conversation"

  /conversations/{conversationId}/messages:
    get:
      tags:
      - "conversations"
      summary: "Get all messages"
      description: "Returns all messages"
      operationId: "getAllMessagesByConversationID"
      produces:
      - "application/json"
      parameters:
      - name: "conversationId"
        in: "path"
        description: "Conversation ID"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
    post:
      tags:
      - "conversations"
      summary: "Echo the sent message"
      description: "Returns the sent message in behalf of the other participant of this conversation"
      operationId: "echoMessage"
      produces:
      - "application/json"
      parameters:
      - name: "conversationId"
        in: "path"
        description: "Conversation ID"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            content:
              type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
        400:
          description: "bad request"
          schema:
            type: "object"
            properties:
              error:
                type: "string"

  /user:
    get:
      tags:
      - "user"
      summary: "Get current user"
      description: "Returns the current user details"
      operationId: "getCurrentUser"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"

definitions:
  Conversation:
    type: "object"
    properties:
      id:
        type: "string"
      participants:
        type: "array"
        items:
          $ref: "#/definitions/User"
      message_url:
        type: "string"

  Message:
    type: "object"
    properties:
      id:
        type: "string"
      created_at:
        type: "string"
      participant:
        $ref: "#/definitions/User"
      content:
        type: "string"

  User:
    type: "object"
    properties:
      id:
        type: "string"
      first_name:
        type: "string"
      last_name:
        type: "string"
      avatar_url:
        type: "string"
